import express from 'express';
import * as cheerio from 'cheerio';

const app = express();
const port = process.env.PORT || 3000;
app.use(express.static('public'));

const UA = 'Mozilla/5.0 (compatible; CryptoScopeCrawler/4.0; +https://example.invalid/bot)';
const TIMEOUT = 10000;
const MAX_CONCURRENCY = 6;
const MAX_CATALOG_PAGES = 30;
const history = new Map();
const cache = { all:{ts:0,data:null}, meme:{ts:0,data:null}, ph:{ts:0,data:null}, global:{ts:0,data:null} };
let telegramOffset = 0;

const csv = v => String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const connectorConfig = {
  discordToken: process.env.DISCORD_BOT_TOKEN || '',
  discordChannels: csv(process.env.DISCORD_CHANNEL_IDS),
  telegramToken: process.env.TELEGRAM_BOT_TOKEN || '',
  telegramPublicChannels: csv(process.env.TELEGRAM_PUBLIC_CHANNELS),
  extraIntelUrls: csv(process.env.EXTRA_INTEL_URLS)
};

const commonSources = [
  { name:'DexScreener', url:'https://dexscreener.com/', type:'market' },
  { name:'GeckoTerminal', url:'https://www.geckoterminal.com/', type:'market' },
  { name:'Etherscan Tokens', url:'https://etherscan.io/tokens', type:'onchain' },
  { name:'Solscan Tokens', url:'https://solscan.io/tokens', type:'onchain' },
  { name:'BscScan Tokens', url:'https://bscscan.com/tokens', type:'onchain' },
  { name:'Reddit CryptoCurrency', url:'https://www.reddit.com/r/CryptoCurrency/', type:'social' },
  { name:'DeFiLlama Unlocks', url:'https://defillama.com/unlocks', type:'tokenomics' },
  { name:'DeFiLlama Hacks', url:'https://defillama.com/hacks', type:'security' },
  { name:'CoinGlass Liquidation', url:'https://www.coinglass.com/LiquidationData', type:'derivatives' },
  { name:'Binance Announcements', url:'https://www.binance.com/en/support/announcement', type:'exchange' },
  { name:'Coinbase Blog', url:'https://www.coinbase.com/blog', type:'exchange' },
  { name:'GitHub Trending', url:'https://github.com/trending', type:'developer' },
  { name:'Fear & Greed', url:'https://alternative.me/crypto/fear-and-greed-index/', type:'macro' }
];
const modeSources = {
  all:[
    {name:'CoinMarketCap',url:'https://coinmarketcap.com/',type:'market'},
    {name:'Google News Crypto',url:'https://news.google.com/rss/search?q=cryptocurrency%20OR%20crypto%20token&hl=en-US&gl=US&ceid=US:en',type:'news'}
  ],
  meme:[
    {name:'CoinMarketCap Memes',url:'https://coinmarketcap.com/view/memes/',type:'market'},
    {name:'Google News Memes',url:'https://news.google.com/rss/search?q=memecoin%20OR%20meme%20coin%20crypto&hl=en-US&gl=US&ceid=US:en',type:'news'},
    {name:'Reddit Memecoins',url:'https://www.reddit.com/r/memecoins/',type:'social'}
  ]
};
const categorySources = [
  ['Meme','meme-token'],['AI','artificial-intelligence'],['DeFi','decentralized-finance-defi'],['RWA','real-world-assets-rwa'],['Gaming','gaming'],['Layer 1','layer-1'],['Layer 2','layer-2'],['Privacy','privacy-coins'],['Exchange','centralized-exchange-token-cex'],['Stablecoin','stablecoins']
];
const fallbackAll=[['BTC','Bitcoin'],['ETH','Ethereum'],['USDT','Tether'],['BNB','BNB'],['SOL','Solana'],['USDC','USDC'],['XRP','XRP'],['DOGE','Dogecoin'],['ADA','Cardano'],['AVAX','Avalanche'],['LINK','Chainlink'],['DOT','Polkadot'],['TRX','TRON'],['SUI','Sui'],['TON','Toncoin'],['UNI','Uniswap'],['AAVE','Aave'],['NEAR','NEAR Protocol']];
const fallbackMeme=[['DOGE','Dogecoin'],['SHIB','Shiba Inu'],['PEPE','Pepe'],['BONK','Bonk'],['WIF','dogwifhat'],['FLOKI','FLOKI'],['BRETT','Brett'],['MOG','Mog Coin'],['POPCAT','Popcat'],['TURBO','Turbo']];
const suspiciousTerms=['guaranteed profit','100x guaranteed','risk free','send funds','presale ending','double your','airdrop claim','wallet validation','connect wallet now','urgent claim','cannot lose','pump now','ape now','next 100x','easy money'];
const bullishTerms=['listing','partnership','upgrade','adoption','integration','volume surge','all time high','breakout','accumulation','whale buy','institutional','mainnet','launch'];
const bearishTerms=['rug pull','rugpull','honeypot','exploit','hack','blacklist','liquidity removed','developer sold','insider dump','scam','delist','lawsuit','breach','unlock'];
const qualityTerms=['mainnet','protocol','validator','governance','staking','revenue','developers','audit','institutional','ecosystem','partnership','integration'];

function timeoutFetch(url,opts={}){const c=new AbortController();const id=setTimeout(()=>c.abort(),TIMEOUT);return fetch(url,{...opts,headers:{'user-agent':UA,'accept-language':'en-US,en;q=0.9',...(opts.headers||{})},signal:c.signal,redirect:'follow'}).finally(()=>clearTimeout(id));}
async function fetchText(src){try{const r=await timeoutFetch(src.url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return{...src,ok:true,text:(await r.text()).slice(0,1800000),status:r.status};}catch(e){return{...src,ok:false,text:'',error:String(e.message||e)};}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let i=0;async function worker(){while(i<items.length){const j=i++;out[j]=await fn(items[j]);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out;}
function cleanText(html){const $=cheerio.load(html||'');$('script,style,noscript,svg').remove();return $('body').text().replace(/\s+/g,' ').trim();}
function extractNews(xml){const $=cheerio.load(xml,{xmlMode:true});const items=[];$('item').slice(0,120).each((_,el)=>items.push({title:$(el).find('title').text(),link:$(el).find('link').text(),published:$(el).find('pubDate').text()}));return items;}
function termCount(text,terms){const t=String(text||'').toLowerCase();return terms.reduce((n,x)=>n+(t.includes(x)?1:0),0);}
function catalogPageCount(html){const $=cheerio.load(html||'');let max=1;$('a[href*="page="]').each((_,a)=>{const m=($(a).attr('href')||'').match(/[?&]page=(\d+)/);if(m)max=Math.max(max,Number(m[1]));});return Math.min(MAX_CATALOG_PAGES,Math.max(1,max));}
function catalogUrl(mode,page){return mode==='meme'?`https://www.coingecko.com/en/categories/meme-token?items=300&page=${page}`:`https://www.coingecko.com/en/coins/all?items=300&page=${page}`;}
async function fetchCatalog(mode){const first=await fetchText({name:mode==='meme'?'CoinGecko Meme 1':'CoinGecko All 1',url:catalogUrl(mode,1),type:'catalog'});if(!first.ok)return[first];const total=catalogPageCount(first.text);const rest=[];for(let p=2;p<=total;p++)rest.push({name:`CoinGecko ${mode==='meme'?'Meme':'All'} ${p}`,url:catalogUrl(mode,p),type:'catalog'});return[first,...await mapLimit(rest,MAX_CONCURRENCY,fetchText)];}
function parseCatalogTokens(pages,mode){const found=new Map();for(const p of pages){if(!p.ok)continue;const $=cheerio.load(p.text||'');$('table tbody tr').each((_,tr)=>{const link=$(tr).find('a[href*="/en/coins/"]').first();if(!link.length)return;const m=(link.attr('href')||'').match(/\/en\/coins\/([^/?#]+)/);if(!m)return;const slug=m[1].toLowerCase();let cell=link.closest('td').text().replace(/\s+/g,' ').trim().replace(/\bBuy\b/gi,'').trim()||link.text().replace(/\s+/g,' ').trim();const parts=cell.split(' ').filter(Boolean);let symbol='';for(let i=parts.length-1;i>=0;i--){const x=parts[i].replace(/^\$+/,'');if(/^[A-Za-z0-9._-]{1,20}$/.test(x)&&/[A-Za-z]/.test(x)){symbol=x.toUpperCase();parts.splice(i,1);break;}}if(!symbol)return;const name=parts.join(' ').trim()||slug.replace(/-/g,' '),id=`cg:${slug}`;if(!found.has(id))found.set(id,{id,slug,symbol,name,mentions:0,catalog:true,categories:mode==='meme'?['Meme']:[],evidenceRecords:[],headlines:[]});});}return found;}
function buildUniverse(catalogPages,mode){const found=parseCatalogTokens(catalogPages,mode),bySymbol=new Map();for(const t of found.values()){if(!bySymbol.has(t.symbol))bySymbol.set(t.symbol,[]);bySymbol.get(t.symbol).push(t);}for(const[s,n]of(mode==='meme'?fallbackMeme:fallbackAll)){if(!bySymbol.has(s)){const t={id:`seed:${s}`,symbol:s,name:n,mentions:0,catalog:false,categories:mode==='meme'?['Meme']:[],evidenceRecords:[],headlines:[]};found.set(t.id,t);bySymbol.set(s,[t]);}}return{found,bySymbol};}
async function fetchCategoryMembership(){return mapLimit(categorySources.map(([label,slug])=>({name:`Category ${label}`,label,url:`https://www.coingecko.com/en/categories/${slug}?items=300&page=1`,type:'category'})),MAX_CONCURRENCY,fetchText);}
function indexCategories(found,pages){const bySlug=new Map([...found.values()].filter(t=>t.slug).map(t=>[t.slug,t]));for(const p of pages){if(!p.ok)continue;const $=cheerio.load(p.text||'');$('a[href*="/en/coins/"]').each((_,a)=>{const m=($(a).attr('href')||'').match(/\/en\/coins\/([^/?#]+)/);const t=m&&bySlug.get(m[1].toLowerCase());if(t&&!t.categories.includes(p.label))t.categories.push(p.label);});}}

function normalizeMessage(m){return String(m||'').toLowerCase().replace(/https?:\/\/\S+/g,'').replace(/[^a-z0-9$ ]/g,' ').replace(/\s+/g,' ').trim();}
function analyzeSocialMessages(messages){const texts=messages.map(m=>normalizeMessage(m.text)).filter(x=>x.length>8),freq=new Map();for(const t of texts)freq.set(t,(freq.get(t)||0)+1);const dupCount=[...freq.values()].filter(n=>n>1).reduce((a,n)=>a+n-1,0);const uniqueAuthors=new Set(messages.map(m=>m.author).filter(Boolean)).size;const suspicious=texts.reduce((a,t)=>a+termCount(t,suspiciousTerms),0);const now=Date.now(),recent=messages.filter(m=>m.ts&&now-m.ts<15*60*1000).length;const prior=messages.filter(m=>m.ts&&now-m.ts>=15*60*1000&&now-m.ts<60*60*1000).length;const burstRatio=prior?Math.min(10,recent/Math.max(1,prior/3)):recent>=10?4:1;const duplicateRatio=texts.length?dupCount/texts.length:0;const authorConcentration=messages.length&&uniqueAuthors?1-Math.min(1,uniqueAuthors/messages.length):0;const risk=Math.round(Math.min(100,duplicateRatio*45+authorConcentration*20+Math.min(25,suspicious*5)+Math.min(20,Math.max(0,burstRatio-1)*5)));return{messages:messages.length,uniqueAuthors,duplicateRatio:Number(duplicateRatio.toFixed(2)),burstRatio:Number(burstRatio.toFixed(2)),suspiciousTerms:suspicious,manipulationRisk:risk};}

async function fetchDiscordIntel(){if(!connectorConfig.discordToken||!connectorConfig.discordChannels.length)return{source:{name:'Discord',type:'social',ok:false,configured:false,error:'Set DISCORD_BOT_TOKEN and DISCORD_CHANNEL_IDS.'},messages:[]};const messages=[];const errors=[];for(const id of connectorConfig.discordChannels){try{const r=await timeoutFetch(`https://discord.com/api/v10/channels/${encodeURIComponent(id)}/messages?limit=100`,{headers:{authorization:`Bot ${connectorConfig.discordToken}`}});if(!r.ok)throw new Error(`channel ${id}: HTTP ${r.status}`);const arr=await r.json();for(const m of Array.isArray(arr)?arr:[]){messages.push({platform:'discord',channel:id,text:m.content||'',author:m.author?.id||'',ts:m.timestamp?Date.parse(m.timestamp):0});}}catch(e){errors.push(String(e.message||e));}}return{source:{name:'Discord',type:'social',ok:messages.length>0,configured:true,error:errors.join('; ')||null},messages,stats:analyzeSocialMessages(messages)};}
async function fetchTelegramBotIntel(){if(!connectorConfig.telegramToken)return{source:{name:'Telegram Bot',type:'social',ok:false,configured:false,error:'Set TELEGRAM_BOT_TOKEN and add the bot to channels/groups.'},messages:[]};try{const u=`https://api.telegram.org/bot${connectorConfig.telegramToken}/getUpdates?timeout=0&limit=100${telegramOffset?`&offset=${telegramOffset}`:''}`;const r=await timeoutFetch(u);if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!d.ok)throw new Error(d.description||'Telegram API error');const messages=[];for(const up of d.result||[]){telegramOffset=Math.max(telegramOffset,(up.update_id||0)+1);const m=up.channel_post||up.message||up.edited_channel_post||up.edited_message;if(!m)continue;messages.push({platform:'telegram',channel:String(m.chat?.id||''),text:m.text||m.caption||'',author:String(m.from?.id||m.sender_chat?.id||''),ts:m.date?m.date*1000:0});}return{source:{name:'Telegram Bot',type:'social',ok:true,configured:true,error:null},messages,stats:analyzeSocialMessages(messages)};}catch(e){return{source:{name:'Telegram Bot',type:'social',ok:false,configured:true,error:String(e.message||e)},messages:[]};}}
async function fetchTelegramPublicIntel(){if(!connectorConfig.telegramPublicChannels.length)return{source:{name:'Telegram Public',type:'social',ok:false,configured:false,error:'Set TELEGRAM_PUBLIC_CHANNELS to public channel usernames.'},messages:[]};const messages=[],errors=[];for(const ch of connectorConfig.telegramPublicChannels){try{const r=await timeoutFetch(`https://t.me/s/${encodeURIComponent(ch.replace(/^@/,''))}`);if(!r.ok)throw new Error(`${ch}: HTTP ${r.status}`);const html=await r.text(),$=cheerio.load(html);$('.tgme_widget_message').slice(-100).each((_,el)=>{const text=$(el).find('.tgme_widget_message_text').text().replace(/\s+/g,' ').trim();const dt=$(el).find('time').attr('datetime');if(text)messages.push({platform:'telegram-public',channel:ch,text,author:ch,ts:dt?Date.parse(dt):0});});}catch(e){errors.push(String(e.message||e));}}return{source:{name:'Telegram Public',type:'social',ok:messages.length>0,configured:true,error:errors.join('; ')||null},messages,stats:analyzeSocialMessages(messages)};}
async function fetchExtraIntel(){if(!connectorConfig.extraIntelUrls.length)return[];return mapLimit(connectorConfig.extraIntelUrls,MAX_CONCURRENCY,(url,i)=>fetchText({name:`Extra Intel ${i+1}`,url,type:'external'}));}
async function fetchAuthorizedSocialIntel(){const [discord,tgBot,tgPublic]=await Promise.all([fetchDiscordIntel(),fetchTelegramBotIntel(),fetchTelegramPublicIntel()]);return{connectors:[discord,tgBot,tgPublic],messages:[...discord.messages,...tgBot.messages,...tgPublic.messages]};}

function indexEvidence(found,bySymbol,pages){for(const p of pages){if(!p.ok||['catalog','category','news'].includes(p.type))continue;const body=p.textIsPlain?p.text:cleanText(p.text),upper=body.toUpperCase(),counts=new Map();for(const m of upper.matchAll(/\b[A-Z][A-Z0-9._-]{1,19}\b/g)){const s=m[0];if(bySymbol.has(s))counts.set(s,Math.min(20,(counts.get(s)||0)+1));}for(const[s,count]of counts)for(const t of bySymbol.get(s)){t.mentions+=count;t.evidenceRecords.push({name:p.name,type:p.type,text:body.slice(0,30000),meta:p.meta||null});}}}
function indexSocialMessages(bySymbol,messages){for(const m of messages){const upper=String(m.text||'').toUpperCase(),matched=new Set();for(const hit of upper.matchAll(/(?:\$)?\b([A-Z][A-Z0-9._-]{1,19})\b/g)){const s=hit[1];if(bySymbol.has(s))for(const t of bySymbol.get(s))matched.add(t);}for(const t of matched){t.mentions++;t.evidenceRecords.push({name:m.platform==='discord'?'Discord':m.platform==='telegram'?'Telegram Bot':'Telegram Public',type:'social',text:m.text||'',meta:{platform:m.platform,channel:m.channel,author:m.author,ts:m.ts}});}}}
function indexNews(bySymbol,items){for(const n of items){const upper=(n.title||'').toUpperCase(),matched=new Set();for(const m of upper.matchAll(/\b[A-Z][A-Z0-9._-]{1,19}\b/g)){if(bySymbol.has(m[0]))for(const t of bySymbol.get(m[0]))matched.add(t);}for(const t of matched){t.headlines.push(n);t.mentions++;t.evidenceRecords.push({name:'Google News',type:'news',text:n.title||''});}}}
function layer(name,types,records,positive=0,negative=0,note=''){const hits=records.filter(r=>types.includes(r.type)),coverage=[...new Set(hits.map(r=>r.name))].length;if(!coverage)return{name,status:'INSUFFICIENT DATA',score:null,coverage:0,note:note||'No token-specific evidence collected from this layer.'};const score=Math.max(0,Math.min(100,50+positive-negative));return{name,status:score>=65?'BULLISH':score<=35?'BEARISH':'NEUTRAL',score,coverage,note};}
function tokenSocialStats(records){const msgs=records.filter(r=>r.type==='social'&&r.meta).map(r=>({text:r.text,author:r.meta.author,ts:r.meta.ts}));return analyzeSocialMessages(msgs);}
function buildIntel(token){const records=token.evidenceRecords||[],text=[...records.map(r=>r.text||''),...(token.headlines||[]).map(h=>h.title||'')].join(' '),bull=termCount(text,bullishTerms),bear=termCount(text,bearishTerms),sus=termCount(text,suspiciousTerms),socialStats=tokenSocialStats(records);const manipulationRisk=Math.max(socialStats.manipulationRisk,Math.min(100,sus*18));const platformNames=[...new Set(records.filter(r=>r.type==='social').map(r=>r.name))];const socialNote=platformNames.length?`Sources: ${platformNames.join(', ')}. ${socialStats.messages} message-level records; ${socialStats.uniqueAuthors} unique authors; duplicate ratio ${Math.round(socialStats.duplicateRatio*100)}%; burst ratio ${socialStats.burstRatio}x.`:'No token-specific social evidence collected.';const layers=[
layer('Market & liquidity',['market','derivatives'],records,Math.min(30,bull*5),Math.min(35,bear*6),'DEX/market and derivatives corroboration.'),
layer('On-chain',['onchain'],records,Math.min(20,bull*4),Math.min(30,bear*6),'Explorer-visible activity; deep wallet attribution still requires chain data.'),
layer('Social',['social'],records,Math.min(24,token.mentions*2),Math.min(35,manipulationRisk*.35),socialNote),
layer('Bot / manipulation',['social'],records,0,manipulationRisk*.5,`Manipulation-risk heuristic ${manipulationRisk}/100. Duplicate ${Math.round(socialStats.duplicateRatio*100)}%, burst ${socialStats.burstRatio}x, suspicious terms ${socialStats.suspiciousTerms}.`),
layer('Tokenomics / unlocks',['tokenomics'],records,0,Math.min(35,bear*6),'Public unlock/tokenomics pages; exact schedules need token-specific confirmation.'),
layer('Security',['security','onchain'],records,Math.min(10,bull*2),Math.min(45,(bear+sus)*8),'Exploit/hack/rug language and explorer corroboration.'),
layer('Exchange',['exchange'],records,Math.min(25,bull*5),Math.min(30,bear*6),'Public listing/delisting and exchange announcements.'),
layer('Developer health',['developer'],records,Math.min(20,termCount(text,qualityTerms)*3),0,'Public developer activity; repository mapping may be incomplete.'),
layer('Catalysts / news',['news','exchange'],records,Math.min(30,bull*6),Math.min(35,bear*7),'Listings, launches, upgrades, partnerships and adverse news.'),
layer('Macro',['macro'],records,Math.min(12,bull*2),Math.min(15,bear*3),'Broad crypto risk environment.'),
layer('Geographic trend',['geo'],records,0,0,'Philippines/global popularity signal when available.')
];const covered=layers.filter(x=>x.score!==null),overall=covered.length?Math.round(covered.reduce((a,x)=>a+x.score,0)/covered.length):null,corroboration=Math.min(100,Math.round((new Set(records.map(r=>r.name)).size/7)*100));return{layers,coveredLayers:covered.length,totalLayers:layers.length,overall,corroboration,manipulationRisk,socialStats,platforms:platformNames,warning:'Scores summarize collected evidence only. Missing layers lower confidence; unavailable evidence is never assumed positive.'};}
function finishScore(token,s){const key=`${s.mode}:${token.id}`,prev=history.get(key)||[];prev.push({t:Date.now(),mentions:token.mentions,opportunity:s.opportunity,risk:s.risk});while(prev.length>40)prev.shift();history.set(key,prev);const older=prev.length>1?prev[Math.max(0,prev.length-6)]:prev[0],momentum=older?token.mentions-older.mentions:0;const intel=buildIntel(token);let confidence=Math.round(Math.min(92,Math.max(15,.62*Math.min(100,s.independentSources*14+(s.marketPresence?14:0)+(s.onchainPresence?14:0)+(s.headlines.length?10:0)+(token.catalog?8:0))+.38*Math.abs(s.opportunity-50)*2)));confidence=Math.round(confidence*Math.max(.5,Math.min(1,intel.coveredLayers/7)));let action='WATCH';if(s.risk>=60||intel.manipulationRisk>=65)action='AVOID';else if(s.opportunity>=76&&s.independentSources>=3&&intel.coveredLayers>=3)action='BUY CANDIDATE';else if(s.opportunity<30)action='AVOID';const risk=Math.max(s.risk,intel.manipulationRisk>=65?65:s.risk),hold=action==='BUY CANDIDATE'?(risk<30&&momentum>=0?'Hold while opportunity remains ≥68 and risk remains controlled; reassess each scan.':'Short-duration setup; reassess on the next scan.'):'No new entry recommended.',exit=action==='BUY CANDIDATE'?'Reduce/exit if opportunity falls below 60, risk rises above 45, manipulation risk spikes, or momentum reverses across consecutive scans.':'N/A';const{evidenceRecords,...clean}=token;return{...clean,opportunity:s.opportunity,risk,rugRisk:risk,quality:s.quality,confidence,action,momentum,independentSources:s.independentSources,bullishSignals:s.bullish,bearishSignals:s.bearish,suspiciousSignals:s.suspicious,evidenceQuality:confidence,hold,exit,evidence:s.names.slice(0,10),headlines:s.headlines,intel};}
function scoreToken(token,mode){const records=token.evidenceRecords||[],headlines=(token.headlines||[]).slice(0,5),text=[...records.map(r=>r.text||''),...headlines.map(x=>x.title||'')].join(' '),bullish=termCount(text,bullishTerms),bearish=termCount(text,bearishTerms),suspicious=termCount(text,suspiciousTerms),qualityHits=termCount(text,qualityTerms),names=[...new Set(records.map(x=>x.name))],independentSources=names.length,marketPresence=records.some(x=>['market','derivatives'].includes(x.type)),onchainPresence=records.some(x=>x.type==='onchain'),categoryBreadth=(token.categories||[]).filter(x=>x!=='Stablecoin').length;let quality=mode==='meme'?null:Math.min(100,35+(token.catalog?15:0)+(onchainPresence?10:0)+Math.min(15,independentSources*3)+Math.min(15,qualityHits*4)+Math.min(10,categoryBreadth*3));let opportunity=(mode==='meme'?30:32)+Math.min(24,token.mentions*2)+bullish*7-bearish*(mode==='meme'?14:10)-suspicious*(mode==='meme'?18:16)+(marketPresence?8:0)+(token.catalog?5:0)+(quality!=null?Math.round((quality-50)*.18):0);opportunity=Math.max(0,Math.min(100,opportunity));let risk=(mode==='meme'?10:18)+bearish*(mode==='meme'?20:13)+suspicious*22+(!onchainPresence?8:0)+(independentSources<2?7:0);risk=Math.max(0,Math.min(100,risk));return finishScore(token,{opportunity,risk,quality,bullish,bearish,suspicious,names,headlines,independentSources,marketPresence,onchainPresence,mode});}

async function runScan(mode='all',force=false){mode=mode==='meme'?'meme':'all';const c=cache[mode];if(!force&&c.data&&Date.now()-c.ts<120000)return c.data;const sourceList=[...commonSources,...modeSources[mode]];const tasks=[fetchCatalog(mode),mapLimit(sourceList,MAX_CONCURRENCY,fetchText),fetchAuthorizedSocialIntel(),fetchExtraIntel()];if(mode==='all')tasks.push(fetchCategoryMembership());const[catalogPages,otherPages,social,extraPages,categoryPages=[]]=await Promise.all(tasks);const{found,bySymbol}=buildUniverse(catalogPages,mode);if(mode==='all')indexCategories(found,categoryPages);indexEvidence(found,bySymbol,[...otherPages,...extraPages]);indexSocialMessages(bySymbol,social.messages);const newsItems=otherPages.filter(p=>p.ok&&p.type==='news').flatMap(p=>extractNews(p.text));indexNews(bySymbol,newsItems);const tokens=[...found.values()].map(t=>scoreToken(t,mode));tokens.sort((a,b)=>(b.action==='BUY CANDIDATE')-(a.action==='BUY CANDIDATE')||b.opportunity-a.opportunity||b.confidence-a.confidence);const sourceHealth=[...catalogPages,...otherPages,...extraPages,...categoryPages,...social.connectors.map(c=>c.source)].map(p=>({name:p.name,type:p.type,ok:!!p.ok,configured:p.configured,error:p.error||null}));const result={mode,generatedAt:new Date().toISOString(),catalogCount:tokens.filter(t=>t.catalog).length,totalTokens:tokens.length,sourceHealth,connectorStats:social.connectors.map(c=>({name:c.source.name,configured:c.source.configured,ok:c.source.ok,error:c.source.error,stats:c.stats||null})),warnings:['Signals are heuristic and do not guarantee profit.','Missing intel is shown as INSUFFICIENT DATA and lowers confidence.','Discord/Telegram access is limited to channels/groups you authorize or public Telegram previews.','Bot/manipulation scores are heuristics, not proof that an account is automated or malicious.'],tokens};cache[mode]={ts:Date.now(),data:result};return result;}

async function fetchTrending(region='global',force=false){region=region==='ph'?'ph':'global';const c=cache[region];if(!force&&c.data&&Date.now()-c.ts<120000)return c.data;const url=region==='ph'?'https://www.coingecko.com/en/highlights/trending-crypto/philippines':'https://www.coingecko.com/en/highlights/trending-crypto';const page=await fetchText({name:region==='ph'?'CoinGecko PH Trending':'CoinGecko Global Trending',url,type:'geo'}),rows=[];if(page.ok){const $=cheerio.load(page.text);$('table tbody tr').each((i,tr)=>{const link=$(tr).find('a[href*="/en/coins/"]').first();if(!link.length)return;const txt=$(tr).text().replace(/\s+/g,' ').trim(),slug=((link.attr('href')||'').match(/\/en\/coins\/([^/?#]+)/)||[])[1]||'',name=link.text().replace(/\s+/g,' ').trim()||slug.replace(/-/g,' '),symbol=(txt.match(/\b[A-Z0-9]{2,12}\b/)||[])[0]||name.slice(0,8).toUpperCase(),token={id:`trend:${region}:${slug||symbol}`,slug,symbol,name,mentions:1,catalog:true,categories:[],evidenceRecords:[{name:page.name,type:'geo',text:txt}],headlines:[]};rows.push({...scoreToken(token,'all'),trendRank:i+1,marketRank:null,price:null,change1h:null,change24h:null,change7d:null,volume24h:null,marketCap:null});});}const result={region,generatedAt:new Date().toISOString(),rows,sourceHealth:[{name:page.name,type:'geo',ok:page.ok,error:page.error||null}]};cache[region]={ts:Date.now(),data:result};return result;}

app.get('/scan',async(req,res)=>{try{res.json(await runScan(req.query.mode,req.query.force==='1'));}catch(e){res.status(500).json({error:String(e.message||e)});}});
app.get('/trending',async(req,res)=>{try{res.json(await fetchTrending(req.query.region,req.query.force==='1'));}catch(e){res.status(500).json({error:String(e.message||e)});}});
app.get('/connectors/status',async(_,res)=>{const social=await fetchAuthorizedSocialIntel();res.json({generatedAt:new Date().toISOString(),discord:{configured:!!connectorConfig.discordToken&&connectorConfig.discordChannels.length>0,channelCount:connectorConfig.discordChannels.length,...social.connectors[0].source,stats:social.connectors[0].stats||null},telegramBot:{configured:!!connectorConfig.telegramToken,...social.connectors[1].source,stats:social.connectors[1].stats||null},telegramPublic:{configured:connectorConfig.telegramPublicChannels.length>0,channelCount:connectorConfig.telegramPublicChannels.length,...social.connectors[2].source,stats:social.connectors[2].stats||null},extraIntelSources:connectorConfig.extraIntelUrls.length});});
app.get('/intel/sources',async(_,res)=>{const [pages,social,extra]=await Promise.all([mapLimit(commonSources,MAX_CONCURRENCY,fetchText),fetchAuthorizedSocialIntel(),fetchExtraIntel()]);res.json({generatedAt:new Date().toISOString(),sources:[...pages.map(p=>({name:p.name,type:p.type,ok:p.ok,error:p.error||null})),...social.connectors.map(c=>c.source),...extra.map(p=>({name:p.name,type:p.type,ok:p.ok,error:p.error||null}))],limits:{discord:'Configure DISCORD_BOT_TOKEN + DISCORD_CHANNEL_IDS; bot needs View Channel, Read Message History and Message Content access.',telegram:'Configure TELEGRAM_BOT_TOKEN for groups/channels where the bot is authorized; TELEGRAM_PUBLIC_CHANNELS can monitor public preview pages.',walletAttribution:'Deep wallet attribution still requires chain nodes or permitted market/on-chain data services.'}});});
app.get('/health',(_,res)=>res.json({ok:true,app:'CryptoScope Intelligence v4',connectors:{discord:!!connectorConfig.discordToken&&connectorConfig.discordChannels.length>0,telegramBot:!!connectorConfig.telegramToken,telegramPublic:connectorConfig.telegramPublicChannels.length>0},now:new Date().toISOString()}));
app.listen(port,()=>console.log(`CryptoScope Intelligence v4 listening on ${port}`));